# Test your FastAPI endpoints

GET http://api.7x24hub.online:6579/wecom-assistant/wechat-agent-callback
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
